FROM mcr.microsoft.com/dotnet/sdk:8.0
WORKDIR /app
EXPOSE 8080
ENV ASPNETCORE_HTTP_PORTS=8080
ENV DOTNET_USE_POLLING_FILE_WATCHER=true

ENTRYPOINT ["dotnet", "watch", "--project", "src/Pipeline.Api/Pipeline.Api.csproj", "run", "--urls", "http://0.0.0.0:8080"]
